### ISSUE TITLE
Complete Profile.js and NotFound.js

### ISSUE THREAD

**Issue by OliverWong0301** [OliverWong0301/Final-FrontEnd#1]
These are located in src/Components

Check all the Front-End source codes and **then complete them**

**Comment by CHICKEN4EVER** [comment]
Like i said i got late today, please help me to complete them.

Ps: Profile.js was linked into the app as a condition in NavBar.js

**Comment by OliverWong0301** [comment]
You complete them tonight

**Comment by CHICKEN4EVER** [comment]
The Profile.js is having an internal server errors 500 at axios.put, please help me to deal with it

**Comment by CHICKEN4EVER** [comment]
NotFound.js is easy and i'll do it soon after Profile.js is completed

**Comment by OliverWong0301** [comment]
Profile.js is completed, added on with createAt data and response in the page.
I'll do the NotFound.js in 2Jan

**Comment by OliverWong0301** [comment]
Everything is done
