### ISSUE TITLE
Save data in the local storage

### ISSUE THREAD

**Issue by OliverWong0301** [OliverWong0301/Final-FrontEnd#3]
We need to save data to the local storage, as we have done in the Final-BackEnd, the login has en expires of requirement of relogin maximum 3 days.

Write the code for that to save token return from database then we can keep loging in until maximum 3 days

**Comment by CHICKEN4EVER** [comment]
Like i said, i got late today. Please help me to complete this

**Comment by OliverWong0301** [comment]
Done. Please have a check for me @CHICKEN4EVER

**Comment by OliverWong0301** [comment]
Checked successfully
